"""
exports/exporter.py
────────────────────────────────────────────────────────────────
Export statistical results and generated bytes to CSV / JSON.
"""

from __future__ import annotations

import csv
import json
import os
import time
from typing import Any


def export_json(data: dict[str, Any], output_path: str) -> str:
    """Serialize *data* to a pretty-printed JSON file."""
    output_path = os.path.abspath(output_path)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
    return output_path


def export_csv(rows: list[dict[str, Any]], output_path: str) -> str:
    """Write *rows* (list of dicts) to a CSV file."""
    if not rows:
        raise ValueError("rows must be non-empty")
    output_path = os.path.abspath(output_path)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return output_path


def build_stats_report(
    results: dict[str, dict],
    sample_size: int,
    timestamp: str | None = None,
) -> dict[str, Any]:
    """
    Build a structured dict suitable for JSON/CSV export.

    Parameters
    ----------
    results : dict
        Mapping of source name → dict with monobit, chi2, runs sub-dicts.
    sample_size : int
    timestamp : str, optional

    Returns
    -------
    dict
    """
    if timestamp is None:
        timestamp = time.strftime("%Y-%m-%dT%H:%M:%S")

    report: dict[str, Any] = {
        "generated_at": timestamp,
        "sample_size_bytes": sample_size,
        "sample_size_bits": sample_size * 8,
        "nist_threshold": 0.01,
        "sources": {},
    }

    for name, res in results.items():
        mb  = res.get("monobit", {})
        chi = res.get("chi2", {})
        runs = res.get("runs", {})
        report["sources"][name] = {
            "monobit": {
                "p_value":   mb.get("p_value"),
                "proportion": mb.get("proportion"),
                "passed":    mb.get("passed"),
            },
            "chi_square": {
                "p_value":   chi.get("p_value"),
                "chi2_stat": chi.get("chi2_stat"),
                "passed":    chi.get("passed"),
            },
            "runs": {
                "p_value":    runs.get("p_value"),
                "runs_count": runs.get("runs_count"),
                "passed":     runs.get("passed"),
            },
            "overall_passed": (
                mb.get("passed", False)
                and chi.get("passed", False)
                and runs.get("passed", False)
            ),
        }

    return report


def build_attack_report(attack_result: Any) -> dict[str, Any]:
    """Convert an AttackResult dataclass to a serialisable dict."""
    return {
        "attack": "MT19937 State Recovery",
        "observed_outputs": attack_result.observed_count,
        "observation_time_ms": round(attack_result.observation_time_ms, 3),
        "clone_time_ms": round(attack_result.clone_time_ms, 3),
        "predictions": [
            {
                "index": i + 1,
                "predicted": f"0x{pred:08X}",
                "actual":    f"0x{actual:08X}",
                "matched":   matched,
            }
            for i, (pred, actual, matched) in enumerate(attack_result.predictions)
        ],
        "accuracy": round(attack_result.accuracy * 100, 1),
        "attack_succeeded": attack_result.attack_succeeded,
        "resistance": {
            "HashPRNG":  not attack_result.hash_prng_predictable,
            "HashDRBG":  not attack_result.hash_drbg_predictable,
        },
    }
